// Code generated by go-swagger; DO NOT EDIT.

// Package restapi DBoM Agent
//
//  The HTTP REST API for the Distributed Bill of Materials Agent
//  Schemes:
//    http
//  Host: localhost:3000
//  BasePath: /
//  Version: 1.0
//  Contact: Ryan<Ryan.Mathison2@unisys.com>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
