// Code generated by go-swagger; DO NOT EDIT.

package record

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewAuditRecordParams creates a new AuditRecordParams object
//
// There are no default values defined in the spec.
func NewAuditRecordParams() AuditRecordParams {

	return AuditRecordParams{}
}

// AuditRecordParams contains all the bound params for the audit record operation
// typically these are obtained from a http.Request
//
// swagger:parameters AuditRecord
type AuditRecordParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Channel ID
	  Required: true
	  In: path
	*/
	ChannelID string
	/*Record ID
	  Required: true
	  In: path
	*/
	RecordID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewAuditRecordParams() beforehand.
func (o *AuditRecordParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rChannelID, rhkChannelID, _ := route.Params.GetOK("channelID")
	if err := o.bindChannelID(rChannelID, rhkChannelID, route.Formats); err != nil {
		res = append(res, err)
	}

	rRecordID, rhkRecordID, _ := route.Params.GetOK("recordID")
	if err := o.bindRecordID(rRecordID, rhkRecordID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindChannelID binds and validates parameter ChannelID from path.
func (o *AuditRecordParams) bindChannelID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.ChannelID = raw

	return nil
}

// bindRecordID binds and validates parameter RecordID from path.
func (o *AuditRecordParams) bindRecordID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.RecordID = raw

	return nil
}
