// Code generated by go-swagger; DO NOT EDIT.

package record

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"trillian-agent/models"
)

// AuditRecordOKCode is the HTTP code returned for type AuditRecordOK
const AuditRecordOKCode int = 200

/*AuditRecordOK Record Audit Trail has been retrieved and is in the body

swagger:response auditRecordOK
*/
type AuditRecordOK struct {

	/*
	  In: Body
	*/
	Payload *models.AuditResponseDefinition `json:"body,omitempty"`
}

// NewAuditRecordOK creates AuditRecordOK with default headers values
func NewAuditRecordOK() *AuditRecordOK {

	return &AuditRecordOK{}
}

// WithPayload adds the payload to the audit record o k response
func (o *AuditRecordOK) WithPayload(payload *models.AuditResponseDefinition) *AuditRecordOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the audit record o k response
func (o *AuditRecordOK) SetPayload(payload *models.AuditResponseDefinition) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AuditRecordOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AuditRecordNotFoundCode is the HTTP code returned for type AuditRecordNotFound
const AuditRecordNotFoundCode int = 404

/*AuditRecordNotFound Channel and/or record does not exist

swagger:response auditRecordNotFound
*/
type AuditRecordNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponseDefinition `json:"body,omitempty"`
}

// NewAuditRecordNotFound creates AuditRecordNotFound with default headers values
func NewAuditRecordNotFound() *AuditRecordNotFound {

	return &AuditRecordNotFound{}
}

// WithPayload adds the payload to the audit record not found response
func (o *AuditRecordNotFound) WithPayload(payload *models.ErrorResponseDefinition) *AuditRecordNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the audit record not found response
func (o *AuditRecordNotFound) SetPayload(payload *models.ErrorResponseDefinition) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AuditRecordNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AuditRecordInternalServerErrorCode is the HTTP code returned for type AuditRecordInternalServerError
const AuditRecordInternalServerErrorCode int = 500

/*AuditRecordInternalServerError Error on agent

swagger:response auditRecordInternalServerError
*/
type AuditRecordInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponseDefinition `json:"body,omitempty"`
}

// NewAuditRecordInternalServerError creates AuditRecordInternalServerError with default headers values
func NewAuditRecordInternalServerError() *AuditRecordInternalServerError {

	return &AuditRecordInternalServerError{}
}

// WithPayload adds the payload to the audit record internal server error response
func (o *AuditRecordInternalServerError) WithPayload(payload *models.ErrorResponseDefinition) *AuditRecordInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the audit record internal server error response
func (o *AuditRecordInternalServerError) SetPayload(payload *models.ErrorResponseDefinition) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AuditRecordInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AuditRecordBadGatewayCode is the HTTP code returned for type AuditRecordBadGateway
const AuditRecordBadGatewayCode int = 502

/*AuditRecordBadGateway Error in repository

swagger:response auditRecordBadGateway
*/
type AuditRecordBadGateway struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponseDefinition `json:"body,omitempty"`
}

// NewAuditRecordBadGateway creates AuditRecordBadGateway with default headers values
func NewAuditRecordBadGateway() *AuditRecordBadGateway {

	return &AuditRecordBadGateway{}
}

// WithPayload adds the payload to the audit record bad gateway response
func (o *AuditRecordBadGateway) WithPayload(payload *models.ErrorResponseDefinition) *AuditRecordBadGateway {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the audit record bad gateway response
func (o *AuditRecordBadGateway) SetPayload(payload *models.ErrorResponseDefinition) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AuditRecordBadGateway) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(502)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
