// Code generated by go-swagger; DO NOT EDIT.

package record

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"

	"trillian-agent/models"
)

// NewCommitRecordParams creates a new CommitRecordParams object
//
// There are no default values defined in the spec.
func NewCommitRecordParams() CommitRecordParams {

	return CommitRecordParams{}
}

// CommitRecordParams contains all the bound params for the commit record operation
// typically these are obtained from a http.Request
//
// swagger:parameters CommitRecord
type CommitRecordParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: body
	*/
	Body *models.RecordDefinition
	/*Channel ID
	  Required: true
	  In: path
	*/
	ChannelID string
	/*Commit Type
	  Required: true
	  In: header
	*/
	CommitType string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewCommitRecordParams() beforehand.
func (o *CommitRecordParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.RecordDefinition
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("body", "body", ""))
			} else {
				res = append(res, errors.NewParseError("body", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(context.Background())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}
	} else {
		res = append(res, errors.Required("body", "body", ""))
	}

	rChannelID, rhkChannelID, _ := route.Params.GetOK("channelID")
	if err := o.bindChannelID(rChannelID, rhkChannelID, route.Formats); err != nil {
		res = append(res, err)
	}

	if err := o.bindCommitType(r.Header[http.CanonicalHeaderKey("commit-type")], true, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindChannelID binds and validates parameter ChannelID from path.
func (o *CommitRecordParams) bindChannelID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.ChannelID = raw

	return nil
}

// bindCommitType binds and validates parameter CommitType from header.
func (o *CommitRecordParams) bindCommitType(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("commit-type", "header", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("commit-type", "header", raw); err != nil {
		return err
	}
	o.CommitType = raw

	return nil
}
