// Code generated by go-swagger; DO NOT EDIT.

package record

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"trillian-agent/models"
)

// RetrieveRecordOKCode is the HTTP code returned for type RetrieveRecordOK
const RetrieveRecordOKCode int = 200

/*RetrieveRecordOK Record has been retrieved and is in the body

swagger:response retrieveRecordOK
*/
type RetrieveRecordOK struct {

	/*
	  In: Body
	*/
	Payload models.ExampleRecordPayloadDefinition `json:"body,omitempty"`
}

// NewRetrieveRecordOK creates RetrieveRecordOK with default headers values
func NewRetrieveRecordOK() *RetrieveRecordOK {

	return &RetrieveRecordOK{}
}

// WithPayload adds the payload to the retrieve record o k response
func (o *RetrieveRecordOK) WithPayload(payload models.ExampleRecordPayloadDefinition) *RetrieveRecordOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the retrieve record o k response
func (o *RetrieveRecordOK) SetPayload(payload models.ExampleRecordPayloadDefinition) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RetrieveRecordOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// RetrieveRecordNotFoundCode is the HTTP code returned for type RetrieveRecordNotFound
const RetrieveRecordNotFoundCode int = 404

/*RetrieveRecordNotFound Channel and/or record does not exist

swagger:response retrieveRecordNotFound
*/
type RetrieveRecordNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponseDefinition `json:"body,omitempty"`
}

// NewRetrieveRecordNotFound creates RetrieveRecordNotFound with default headers values
func NewRetrieveRecordNotFound() *RetrieveRecordNotFound {

	return &RetrieveRecordNotFound{}
}

// WithPayload adds the payload to the retrieve record not found response
func (o *RetrieveRecordNotFound) WithPayload(payload *models.ErrorResponseDefinition) *RetrieveRecordNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the retrieve record not found response
func (o *RetrieveRecordNotFound) SetPayload(payload *models.ErrorResponseDefinition) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RetrieveRecordNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RetrieveRecordInternalServerErrorCode is the HTTP code returned for type RetrieveRecordInternalServerError
const RetrieveRecordInternalServerErrorCode int = 500

/*RetrieveRecordInternalServerError Error on agent

swagger:response retrieveRecordInternalServerError
*/
type RetrieveRecordInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponseDefinition `json:"body,omitempty"`
}

// NewRetrieveRecordInternalServerError creates RetrieveRecordInternalServerError with default headers values
func NewRetrieveRecordInternalServerError() *RetrieveRecordInternalServerError {

	return &RetrieveRecordInternalServerError{}
}

// WithPayload adds the payload to the retrieve record internal server error response
func (o *RetrieveRecordInternalServerError) WithPayload(payload *models.ErrorResponseDefinition) *RetrieveRecordInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the retrieve record internal server error response
func (o *RetrieveRecordInternalServerError) SetPayload(payload *models.ErrorResponseDefinition) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RetrieveRecordInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RetrieveRecordBadGatewayCode is the HTTP code returned for type RetrieveRecordBadGateway
const RetrieveRecordBadGatewayCode int = 502

/*RetrieveRecordBadGateway Error in repository

swagger:response retrieveRecordBadGateway
*/
type RetrieveRecordBadGateway struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponseDefinition `json:"body,omitempty"`
}

// NewRetrieveRecordBadGateway creates RetrieveRecordBadGateway with default headers values
func NewRetrieveRecordBadGateway() *RetrieveRecordBadGateway {

	return &RetrieveRecordBadGateway{}
}

// WithPayload adds the payload to the retrieve record bad gateway response
func (o *RetrieveRecordBadGateway) WithPayload(payload *models.ErrorResponseDefinition) *RetrieveRecordBadGateway {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the retrieve record bad gateway response
func (o *RetrieveRecordBadGateway) SetPayload(payload *models.ErrorResponseDefinition) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RetrieveRecordBadGateway) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(502)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
