// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RecordDefinition RecordDefinition
// Example: {"recordID":"exampleRecord","recordIDPayload":{"example":"example"}}
//
// swagger:model RecordDefinition
type RecordDefinition struct {

	// record ID
	// Required: true
	RecordID *string `json:"recordID"`

	// record ID payload
	// Required: true
	RecordIDPayload interface{} `json:"recordIDPayload"`
}

// Validate validates this record definition
func (m *RecordDefinition) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRecordID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRecordIDPayload(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RecordDefinition) validateRecordID(formats strfmt.Registry) error {

	if err := validate.Required("recordID", "body", m.RecordID); err != nil {
		return err
	}

	return nil
}

func (m *RecordDefinition) validateRecordIDPayload(formats strfmt.Registry) error {

	if m.RecordIDPayload == nil {
		return errors.Required("recordIDPayload", "body", nil)
	}

	return nil
}

// ContextValidate validates this record definition based on context it is used
func (m *RecordDefinition) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RecordDefinition) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RecordDefinition) UnmarshalBinary(b []byte) error {
	var res RecordDefinition
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
